#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

social:
  auth:
    url: http://106.74.154.90:18491/oauth/oauth/check_token/outer
    source: LJPT
